version: '2.3'

services:
  splunk:
    image: splunk/splunk
    environment:
      - SPLUNK_USER=root
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_ENABLE_LISTEN=9997
    ports:
      - 8001:8000
      - 8088:8088

  spring-boot-rest-example:
    image: spring-boot-rest-example:0.6
    volumes:
     - ./conf:/usr/local/apache2/conf
    environment:
      - revision={.tag}
    ports:
      - "8090:8090"
      - "8091:8091"
    logging:
      driver: splunk
      options:
        splunk-token: 5716c24c-9be4-47e3-8e8e-eac27494020e
        splunk-url: "http://localhost:8088"
        splunk-format: json

  apache-app:
    image: apache-app:0.2
    ports:
      - "8002:80"
    logging:
      driver: splunk
      options:
        splunk-token: 5716c24c-9be4-47e3-8e8e-eac27494020e
        splunk-url: "http://localhost:8088"
        splunk-format: json
